config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  namespace :admin do # на стороне админа
    resources :badges
  end

  resources :badges, only: %i[index] # на стороне юзера для проверки пройденных и непройденных бейджей

  namespace :admin do
    resources :gists, only: %i[index]
  end

  resources :gists, only: %i[create]

  resources :feedback, only: %i[index create]
  
end

app/models/badge.rb
class Badge < ApplicationRecord

  has_many :badges_users, dependent: :destroy
  has_many :users, through: :badges_users

  validates :title, :img_url, :condition, :description, presence: true
  
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController

  before_action :set_badge, only: %i[destroy show edit update]

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def edit

  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  def show

  end

  def destroy
    @badge.destroy

    redirect_to admin_badges_path
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:title, :img_url, :condition, :description, :condition_value)
  end

  def condition
    @conditions = Condition.all
  end

end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  
  before_action :authenticate_user!

  def index
    @badges = Badge.all
    current_user.badges
  end
  
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class="text-center"><%= badge.title %></td>
  <td class="text-center"><%= link_to t('.show'), admin_badge_path(badge) %></td>
  <td class="text-center"><%= link_to t('.edit'), edit_admin_badge_path(badge) %></td>
  <td class="text-center">
    <%= link_to t('.delete'), 
                admin_badge_path(badge), 
                method: :delete, 
                data: { confirm: t('.confirmation')} %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with(model:[:admin, @badge]) do |form| %>
  <%= render 'shared/errors', resource: @badge %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, id: :badge_name, class: "form-control" %>
  </p>

  <p>
    <%= form.label :image %>
    <%= form.text_field :img_url, id: :badge_image, class: "form-control"  %>
  </p>

  <p>
    <%= form.label :condition %>
    <%= form.collection_select :condition, Condition.all, :title, :title, {prompt: true}, {class: "form-select"} %>
  </p>

  <p>
    <%= form.label :condition_value %>
    <%= form.text_field :condition_value, id: :badge_condition_value, class: "form-control" %>
  </p>
  
  <p>
    <%= form.label :description %>
    <%= form.text_area :description, id: :badge_description, class: "form-control" %>
  </p>

  <p><%= form.submit class: 'btn btn-primary' %></p>

<% end %>

app/views/admin/badges/edit.html.erb
<div class="row">  
  <div class="col col-md-4">
    <h1><%= t('.header') %></h1>

    <%= render 'form' %>
    <p>
      <%= link_to t('.back'), admin_badges_path %>
    </p>
  </div>
</div>  

app/views/admin/badges/index.html.erb
<div class="row">  
  <div class="col col-md-4">
    <h1><%= t('.header') %></h1>

    <p>
      <%= link_to t('.new_badge'), new_admin_badge_path %>
    </p>

    <table>
      <thead>
        <tr>
          <th class="text-center"><%= t('.title') %></th>
          <th colspan="3" class="text-center"><%= t('.action') %></th>
        </tr>
      </thead>

      <%= render @badges %>
    </table><br>

    <p>
      <%= link_to t('.back'), admin_tests_path %>
    </p>
  </div>
</div>  

app/views/admin/badges/new.html.erb
<div class="row">  
  <div class="col col-md-4">
    <h1><%= t('.header') %></h1>

    <%= render 'form' %>
    <p>
      <%= link_to t('.back'), admin_badges_path %>
    </p>
  </div>
</div>

app/views/admin/badges/show.html.erb
<div class="row">  
  <div class="col col-md-4">
    <div class="card" style="width: 15rem;">
      <img src="<%= @badge.img_url %>" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title"><%= @badge.title %></h5>
        <p class="card-text"><%= @badge.description %></p>
      </div>
    </div>

    <p>
      <%= link_to t('.back'), admin_badges_path %>
    </p>
  </div>
</div>  