config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  namespace :admin do # на стороне админа
    resources :badges
  end

  resources :badges, only: %i[index] # на стороне юзера для проверки пройденных и непройденных бейджей

  namespace :admin do
    resources :gists, only: %i[index]
  end

  resources :gists, only: %i[create]

  resources :feedback, only: %i[index create]
  
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :badges_tests, dependent: :destroy
  has_many :badges, through: :badges_tests

  validates :title, presence: true
  validates :title, uniqueness: { scope: :level,
    message: "С данным уровнем тест уже существует" }
  validates :level, numericality: { only_integer: true }

  scope :level_selection, -> (level) { where(level: level) }

  scope :easy, -> { level_selection(0..1) }
  scope :normal, -> { level_selection(2..4) }
  scope :heavy, -> { level_selection(5..Float::INFINITY) }
  
  scope :by_level,
        lambda { |level|
          where('level = ?', level)
        }

  scope :category_selection, -> (category) { where(category_id: category) }

  scope :backend, -> { category_selection(2) }
  scope :frontend, -> { category_selection(3) }
  scope :mobile_development, -> { category_selection(4) }

  scope :by_category,
        lambda { |category|
          joins(:category)
            .where('categories.title = ?', category)
        }

  # default_scope { order(title: :asc) } # закомментировал данный скоуп и эту сортировку добавил в метод класса

  scope :with_category, -> (category) { joins(:category).where(categories: {title: category})}

  def self.test_with_category(category)
    Test.with_category(category).order(title: :asc).pluck(:title)
  end

  scope :publication, -> { where(publication: true) }
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true
  has_many :badges

  before_validation :before_validation_set_first_and_next_question

  SUCCES_RATE = 85

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def answer_selected?(answer_ids)
    answer_ids.nil?
  end

  def percentage_formula
    ( correct_questions * 100 ) / test.question_ids.size
  end
  
  def success?
    percentage_formula >= SUCCES_RATE
  end

  def progress_bar_formula
    100 / test.question_ids.size
  end

  def question_index_formula(index)
    test.question_ids.index(index) + 1
  end

  def test_time
    test.test_time
  end

  def deadline_date
    created_at + (test_time * 60)
  end

  def expired?
    Time.new >= deadline_date
  end

  private

  def before_validation_set_first_and_next_question
    if current_question.present?
      set_next_question
    else
      set_first_question
    end
  end

  def set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def set_next_question
    next_question = test.questions.order(:id).where('id > ?', current_question.id).first
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result]
  
  def show

  end

  def result

  end

  def update
    if @test_passage.answer_selected?(params[:answer_ids])
      flash[:alert] = t('.failure')
      render :show
    else
      @test_passage.accept!(params[:answer_ids])

      if @test_passage.expired? || @test_passage.completed?
        award_user(@test_passage)
        TestsMailer.completed_test(@test_passage).deliver_now
        redirect_to result_test_passage_path(@test_passage)
      else
        render :show
      end
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def award_user(test_passage)
    award = BadgeAwardService.new(test_passage).call
    current_user.badges.push(award)
  end

end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/_countdown.html.erb
<div><%= t('.test_time') %></div>
<div class="timer">
  <div class="timer__items"
    data-deadline_date="<%= @test_passage.deadline_date %>">

    <div class="timer__item timer__hours">00</div>
    <div class="timer__item timer__minutes">00</div>
    <div class="timer__item timer__seconds">00</div>
  </div>
</div>

app/views/test_passages/_progress_bar.html.erb
<div class="progress-bar" 
     data-progress-fill="<%= @test_passage.progress_bar_formula %>"
     data-question-index="<%= @test_passage.question_index_formula(@test_passage.current_question.id) %>">
  <div class="progress-fill"></div>
  <span class="progress-text"></span>
</div>
<br>

app/views/test_passages/result.html.erb
<div class="row">  
  <div class="col col-md-4">  
    <h1><%= t('.header' ,title: @test_passage.test.title) %></h1>

    <h2> <% if @test_passage.success? %> </h2>
    <h2 style="color:#32CD32"><%= t('.successful_result', success: @test_passage.percentage_formula) %></h2>
    <h2> <% else %> </h2>
    <h2 style="color:#ff0000"><%= t('.failed_result', success: @test_passage.percentage_formula) %></h2>
    <h2> <% end %> </h2>

    <%= link_to t('.all_test'), tests_path %>
  </div>
</div>  

app/views/test_passages/show.html.erb
<div class="row">
  <div class="col col-md-12">
    <h1><%= t('.header' ,title: @test_passage.test.title) %></h1>

    <%= render 'countdown' %>
    <%= render 'progress_bar' %>

    <b>
    <% @test_passage.test.question_ids.each_with_index do |name, index| %>
      <% if "#{name}" == "#{@test_passage.current_question.id}" %>
        <%= t('.questions', index: index + 1, question_size: @test_passage.test.question_ids.size,) %>
      <% end %>
    <% end %>
    </b><br>

    <b>
      <%= @test_passage.current_question.body %>
    </b>

    <%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
      <div class="form-check">
        <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
          <p>
            <%= b.check_box id: "answer_ids_#{b.object.id}", class: 'form-check-input' %>
            <%= b.label %>
          </p>
        <% end %>
      </div>

      <p><%= link_to 'Gist Question', gists_path(test_passage_id: @test_passage.id), method: :post %></p>
      <p><%= form.submit t('.next'), class: 'btn btn-primary' %></p>
    <% end %>
  </div>
</div>