config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  namespace :admin do # на стороне админа
    resources :badges
  end

  resources :badges, only: %i[index] # на стороне юзера для проверки пройденных и непройденных бейджей

  namespace :admin do
    resources :gists, only: %i[index]
  end

  resources :gists, only: %i[create]

  resources :feedback, only: %i[index create]
  
end

app/models/admin.rb
class Admin < User

  validates :first_name, presence: true
  validates :last_name, presence: true

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :num_of_answers_for_questions

  scope :correct, -> { where(correct: true) }
  
  def num_of_answers_for_questions
    errors.add(:question) if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord

  has_many :badges_users, dependent: :destroy
  has_many :users, through: :badges_users

  validates :title, :img_url, :condition, :description, presence: true
  
end

app/models/badges_user.rb
class BadgesUser < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/models/condition.rb
class Condition < ApplicationRecord
end

app/models/feedback.rb
class Feedback < ApplicationRecord

  belongs_to :user

  validates :body, presence: true

end

app/models/gist.rb
class Gist < ApplicationRecord

  belongs_to :question
  belongs_to :user

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/rule.rb
class Rule < ApplicationRecord
  has_many :badges, dependent: :destroy
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :badges_tests, dependent: :destroy
  has_many :badges, through: :badges_tests

  validates :title, presence: true
  validates :title, uniqueness: { scope: :level,
    message: "С данным уровнем тест уже существует" }
  validates :level, numericality: { only_integer: true }

  scope :level_selection, -> (level) { where(level: level) }

  scope :easy, -> { level_selection(0..1) }
  scope :normal, -> { level_selection(2..4) }
  scope :heavy, -> { level_selection(5..Float::INFINITY) }
  
  scope :by_level,
        lambda { |level|
          where('level = ?', level)
        }

  scope :category_selection, -> (category) { where(category_id: category) }

  scope :backend, -> { category_selection(2) }
  scope :frontend, -> { category_selection(3) }
  scope :mobile_development, -> { category_selection(4) }

  scope :by_category,
        lambda { |category|
          joins(:category)
            .where('categories.title = ?', category)
        }

  # default_scope { order(title: :asc) } # закомментировал данный скоуп и эту сортировку добавил в метод класса

  scope :with_category, -> (category) { joins(:category).where(categories: {title: category})}

  def self.test_with_category(category)
    Test.with_category(category).order(title: :asc).pluck(:title)
  end

  scope :publication, -> { where(publication: true) }
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true
  has_many :badges

  before_validation :before_validation_set_first_and_next_question

  SUCCES_RATE = 85

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def answer_selected?(answer_ids)
    answer_ids.nil?
  end

  def percentage_formula
    ( correct_questions * 100 ) / test.question_ids.size
  end
  
  def success?
    percentage_formula >= SUCCES_RATE
  end

  def progress_bar_formula
    100 / test.question_ids.size
  end

  def question_index_formula(index)
    test.question_ids.index(index) + 1
  end

  def test_time
    test.test_time
  end

  def deadline_date
    created_at + (test_time * 60)
  end

  def expired?
    Time.new >= deadline_date
  end

  private

  def before_validation_set_first_and_next_question
    if current_question.present?
      set_next_question
    else
      set_first_question
    end
  end

  def set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def set_next_question
    next_question = test.questions.order(:id).where('id > ?', current_question.id).first
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  has_many :categories, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :tests_created, class_name: 'Test', foreign_key: :author_id
  has_many :gists, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
  has_many :badges_users, dependent: :destroy
  has_many :badges, through: :badges_users

  validates :user_name, :user_surname, presence: true

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def ended_on_level(level)
    tests.level_selection(level)
  end

  def admin?
    is_a?(Admin)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper

  def correct_true_and_false
    if @answer.correct
      t('helpers.answers_helper.correct_true_and_false.true')
    else
      t('helpers.answers_helper.correct_true_and_false.false')
    end
  end

end

app/helpers/devise_helper.rb
# frozen_string_literal: true

module DeviseHelper
  # Retain this method for backwards compatibility, deprecated in favor of modifying the
  # devise/shared/error_messages partial.
  def devise_error_messages!
    Devise.deprecator.warn <<-DEPRECATION.strip_heredoc
      [Devise] `DeviseHelper#devise_error_messages!` is deprecated and will be
      removed in the next major version.

      Devise now uses a partial under "devise/shared/error_messages" to display
      error messages by default, and make them easier to customize. Update your
      views changing calls from:

          <%= devise_error_messages! %>

      to:

          <%= render "devise/shared/error_messages", resource: resource %>

      To start customizing how errors are displayed, you can copy the partial
      from devise to your `app/views` folder. Alternatively, you can run
      `rails g devise:views` which will copy all of them again to your app.
    DEPRECATION

    return "" if resource.errors.empty?

    render "devise/shared/error_messages", resource: resource
  end
  
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper

  def question_header(question)
    if question.persisted?
      t("helpers.questions_helper.question_header.edit", title: question.test.title)
    else
      t("helpers.questions_helper.question_header.create", title: question.test.title)
    end
  end

end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/admin/_nav.html.erb
<div class="nav nav-admin">
  <span class="nav-admin title"><%= t('.header') %></span>

  <div class="nav-admin user">
    <%= t('.welcome') %>, <b class="nav-admin user-email"><%= current_user.email %></b> Guru |
    <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<nav class="navbar bg-body">
  <div class="container-fluid"> 
    <div class="card-body">
        <h1 class="card-title", style="font-size: 16px;"><%= t(".author") %></h1>

        <ul style="font-size: 15px;">
          <li><%= link_to t(".project"), "https://www.thinknetica.com", target: :blank %></li>
          <li><%= github_url('PavelZelenkov', 'Base_Rails') %></li>
          <li><%= link_to t(".more_project_author"), "http://127.0.0.1:3000/about.html" %></li>
        </ul>

        <div><%= this_year %></div>
    </div>
  </div>
</nav>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <p class="nav user">
    <%= t('.welcome') %>, <b><%= current_user.email %></b> Guru |
    <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
  </p>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Admin Panel | TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/nav" %>

    <div class="container-fluid">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/nav" %>

    <div class="container-fluid">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
 
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2>
      <%= t('.header', count: resource.errors.count) %>:
    </h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-12">    
    <% flash.each do |type, message| %>
      <% if flash[type] == flash[:alert] %>
        <div class="alert alert-danger" role="alert">
          <%= content_tag :p, message.html_safe, class: "flash #{type}" %>
        </div>
      <% else %>
        <div class="alert alert-primary" role="alert">
          <%= content_tag :p, message.html_safe, class: "flash #{type}" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <span class="navbar-text">
      <% if current_user != nil && current_user.admin? %>
        <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
        <div class="vr"></div>
        <%= link_to admin_tests_path, class: 'navbar-brand' do %>
          <i class="bi bi-tools"></i>
        <% end %>

      <% else %>
        <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
      <% end %>
    </span>
    
    <span class="navbar-text">
      <% if user_signed_in? %>
        <%= t('.welcome') %>, <b><%= current_user.email %></b> Guru |
        <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to t('.log_in'), new_session_path(resource_name) %> |
        <%= link_to t('.sign_up'), new_registration_path(resource_name) %>
      <% end %>
    </span>
  </div>
</nav>