config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  namespace :admin do # на стороне админа
    resources :badges
  end

  resources :badges, only: %i[index] # на стороне юзера для проверки пройденных и непройденных бейджей

  namespace :admin do
    resources :gists, only: %i[index]
  end

  resources :gists, only: %i[create]

  resources :feedback, only: %i[index create]
  
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController

  before_action :set_test, only: %i[new create]
  before_action :set_the_question, only: %i[destroy show edit update]

  rescue_from ActiveRecord::RecordNotFound, :with => :rescue_with_question_not_found

  def destroy
    @question.destroy

    redirect_to admin_test_path(@question.test)
  end

  def show

  end

  def new
    @question = @tests.questions.new
  end

  def edit

  end

  def create
    @question = @tests.questions.new(question_params)
    if @question.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render :edit
    end
  end

  private

  def set_test
    @tests = Test.find(params[:test_id])
  end

  def set_the_question
    @question = Question.find(params[:id])
  end
  
  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: 'Question was not found'
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper

  def question_header(question)
    if question.persisted?
      t("helpers.questions_helper.question_header.edit", title: question.test.title)
    else
      t("helpers.questions_helper.question_header.create", title: question.test.title)
    end
  end

end

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.body %></td>
  <td class="text-center"><%= link_to t('.show'), admin_question_path(question) %></td>
  <td class="text-center"><%= link_to t('.edit'), edit_admin_question_path(question) %></td>
  <td class="text-center"><%= link_to t('.delete'), admin_question_path(question), method: :delete, data: { confirm: t('.confirmation')} %></td>
</tr>

app/views/admin/questions/edit.html.erb
<div class="row">  
  <div class="col col-md-4">    
    <h1><%= question_header(@question) %></h1>

    <%= form_with(model:[:admin, @question]) do |form| %>
      <%= render 'shared/errors', resource: @question %>

      <p>
        <%= form.label :body %><br>
        <%= form.text_field :body, class: "form-control" %>
      </p>

      <p><%= form.submit class: 'btn btn-primary' %></p>
    <% end %>

    <%= link_to t('.back'), admin_test_path(@question.test) %>
  </div>
</div>

app/views/admin/questions/index.html.erb
# <h1>All Questions - <%= @tests.title %></h1>
# <h2>Level: <%= @tests.level %></h2>

# <p>
#   <%= link_to 'New question', new_test_question_path %>
# </p>

# <table>
#   <tr>
#     <th>Questions:</th>
#   </tr>

#   <% @question.each do |question| %>
#     <tr>
#       <td><%= question.body %></td>
#     </tr>
#   <% end %>
# </table>

app/views/admin/questions/new.html.erb
<div class="row">  
  <div class="col col-md-4">    
    <h1><%= question_header(@question) %></h1>

    <%= form_with(model:[:admin, @tests, @question]) do |form| %>
      <%= render 'shared/errors', resource: @question %>

      <p>
        <%= form.label :body %><br>
        <%= form.text_field :body, class: "form-control" %>
      </p>

      <p><%= form.submit class: 'btn btn-primary' %></p>
    <% end %>

    <%= link_to t('.back'), admin_test_path(@tests) %>
  </div>
</div>

app/views/admin/questions/show.html.erb
<div class="row">  
  <div class="col col-md-4">    
    <h1><%= @question.body %></h1>

    <h2><%= t('.answers') %></h2>

    <%= link_to t('.new_answer'), new_admin_question_answer_path(@question) %>

    <ol>
      <%= render @question.answers %>
    </ol>

    <%= link_to t('.back'), admin_test_path(@question.test) %> |
    <%= link_to t('.edit'), edit_admin_question_path(@question) %> |
    <%= link_to t('.delete'), admin_question_path(@question), method: :delete, data: { confirm: t('.confirmation')} %>
  </div>
</div>